name: "🚀 publish"
on: 
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v1
      - name: 🟢 node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.com/
      - name: ⚙ install packages        
        run: npm install
      - name: 🧪 test        
        run: npm test
      - name: 🚀 publish
        run: npm publish --access public
        env:
            token: ${{ secrets.NPM_AUTH_TOKEN }}
